### ISSUE TITLE
Is it possible to use GeoIP databases with additional information?

### ISSUE THREAD

**Issue by kbzowski** [plausible/hosting#109]
The readme only gives the IP-Cities database as an example. Can I use, for example, the GeoIP2-ISP database to also see ISP information?

**Comment by ruslandoga** [comment]
👋 @kbzowski 

It'd be great if you try and then we'd update the readme.

**Comment by ruslandoga** [comment]
Ah, sorry. I thought you meant an alternative MMDB provider. What is GeoIP2-ISP?

**Comment by kbzowski** [comment]
This is one of the Maxmind paid databases.
https://www.maxmind.com/en/geoip-databases#buy-now
It contains also information about ISP

**Comment by ruslandoga** [comment]
The ISP information would most likely be ignored. [Only `city`, `country`, and `subdivisions` fields are being looked up right now.](https://github.com/plausible/analytics/blob/ba5b80a8c0dde2c982c7bf77547923244c6d8110/lib/plausible/ingestion/geolocation.ex#L4-L25)
