### ISSUE TITLE
Arm64 Images support

### ISSUE THREAD

**Issue by surapuramakhil** [plausible/hosting#115]
Please do not submit issues here. Best place for self-hosting issues, questions and ideas is [the community forum here on GitHub](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

Support for Arm64 architecture

**Comment by ruslandoga** [comment]
👋 @surapuramakhil 

It's already supported :)

**Comment by ruslandoga** [comment]
If you are referring to the `mail` service, then it's going to be removed in v2.1.0.
