### ISSUE TITLE
Feature Request: Expose custom JS API to detect unique user/visitor

### ISSUE THREAD

**Issue by kurdin** [plausible/hosting#120]
I use Plausible to track unique users for my Tauri App (Windows and Mac). I have the users' unique device ID that I want to use to determine if a user is unique or not. It would be nice to have something like a `window.plausible.setUniqueVisitorId` that enables me to specify the method for tracking individual visitors or users in Plausible.

**Comment by ruslandoga** [comment]
👋 @kurdin 

I think https://feedback.plausible.io is what's being used for feature requests. This repo and the corresponding issues are about an example self-hosted setup.
