### ISSUE TITLE
Clickhouse version 23.3 no longer supported

### ISSUE THREAD

**Issue by dimejo** [plausible/hosting#121]
The Clickhouse server version used in [docker-compose.yml](https://github.com/plausible/community-edition/blob/2703326e60ee834528b9a47902d1bbf1035ba4fc/docker-compose.yml#L18) is no longer supported. The [Clickhouse versioning policy](https://yandex.cloud/en/docs/managed-clickhouse/concepts/update-policy) only supports LTS versions for a period of 12 months.

Are newer versions of Clickhouse compatible with Plausible v2.0.0?

PS: Is there a reason why `docker-compose.yml` is using a specific version of Clickhouse (`23.3.7.5`) instead of a branch tag like `23.3`?

**Comment by ruslandoga** [comment]
👋 @dimejo 

> Are newer versions of Clickhouse compatible with Plausible v2.0.0?

They should be, I tried 24.3 recently.

>  Is there a reason why docker-compose.yml is using a specific version of Clickhouse (23.3.7.5) instead of a branch tag like 23.3?

Plausible Cloud is using `23.3.7.5`, that's the only reason :)

**Comment by ruslandoga** [comment]
Plausible Cloud just [started](https://github.com/plausible/analytics/pull/4062) using 24.3.3.102 and I updated the pre-release v2.1.0 Docker Compose config: https://github.com/plausible/community-edition/commit/ea233ce9202a7217a7425c83fe6ec94de7471907

**Comment by dimejo** [comment]
Great, thanks for the fast update!
