### ISSUE TITLE
Preview doesn't load

### ISSUE THREAD

**Issue by zipposativ** [plausible/hosting#131]
Hi, I have switched to the latest version. Since then I haven't been able to see any previews. Version [v2.1.0]

![plausible](https://github.com/plausible/community-edition/assets/104485696/6895043e-a87e-48ee-8548-040bafdd3b60)

**Comment by ruslandoga** [comment]
👋 @zipposativ 

If you are using a reverse proxy, please check that it allows WebSocket connections.

**Comment by zipposativ** [comment]
Thanks @ruslandoga, it works!
