### ISSUE TITLE
City level data?

### ISSUE THREAD

**Issue by AsyncPiMaker** [plausible/hosting#14]
How can I use city level data from MaxMinds?

I tried this in the geoip environment:

      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City

And this in the plausible environment:

      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-City.mmdb

But only see country level data in my dashboard.  Am I missing a configuration option? Or is this level of detail a potential new feature/enhancement?

Great job!  Many thanks for this alternative platform!

**Comment by ukutaht** [comment]
Hi, city level data is not supported by the platform yet. Please follow #102 to get updates on that.
