### ISSUE TITLE
Import CSV failed with no explanation

### ISSUE THREAD

**Issue by saeedesmaili** [plausible/hosting#143]
I'm using v2.1.1, and tried to convert the data export I got from my simpleanalytics account to the format [that works with Plausible](https://plausible.io/docs/csv-import#csv-format-guidelines), but for some files (`locations`, `operating systems`, `browsers`) I get the following error when importing into Plausible:

<img width="789" alt="image" src="https://github.com/user-attachments/assets/6204252f-c1f5-4a7e-a090-c98ac281ff0d">

It's frustrating, since I tried many things, I double checked with the csv files exported from Plausible, double checked the desired format of columns, etc, but I still can't figure out what's causing this error. Where can I find an error log on this? The docker container doesn't have any errors related to this.

**Comment by ruslandoga** [comment]
👋 @saeedesmaili 

You can try checking `errors` column in `oban_jobs` table in your PostgreSQL database.

**Comment by saeedesmaili** [comment]
@ruslandoga Thanks, I found the issue using the error log in `oban_jobs`. It would be nice to have these errors somewhere in the UI.

**Comment by Aboitier** [comment]
Hi, following-up on this.

I am also trying to import a CSV file to one of my websites. I also double-checked everything but I have no errors : it only greys out and say nothing else. I am using v2.1.3.

If I retry the import, a yellow warning shows up saying : 
```
Dates Adjusted

The dates 2014-10-21 to 2023-02-09 overlap with previous imports, so we'll use the next best period, 2014-10-21 to 2023-02-08
```

But when I go back to `/website.com/settings/imports-exports`, existing imports section is blank.

Nothing shows up related to this error in my pg_db when I run : 
`SELECT * FROM oban_jobs ORDER BY inserted_at DESC;`

Any hint ?

**Comment by ruslandoga** [comment]
👋 @Aboitier 

Would you be able to share your `docker compose logs`? I think it might be related to https://github.com/plausible/analytics/issues/4638.

~~I added a commit that mounts /tmp to a volume https://github.com/plausible/community-edition/commit/de386c2893ec15329145d87ca15a2c0a255547b9 this might resolve this error.~~ Doesn't seem to help.

**Comment by Aboitier** [comment]
Thanks for the rapid answer.

Here is an extract from the csv I try to import, which is named `imported_visitors_20141021_20230209` : 

```
"date","visitors","pageviews","bounces","visits","visit_duration"
"2014-10-21",17,96,6,23,9055
"2014-10-22",9,36,3,10,2457
"2014-10-23",9,25,5,9,187
"2014-10-24",8,29,2,9,3842
"2014-10-25",3,3,3,3,0
"2014-10-26",5,11,4,6,100
"2014-10-27",14,76,9,21,9346
"2014-10-28",10,21,9,13,349
"2014-10-29",4,38,1,5,3568
"2014-10-30",7,16,5,8,575
"2014-10-31",2,19,1,2,976
"2014-11-01",3,3,3,3,0
"2014-11-02",6,7,5,6,43
"2014-11-03",10,53,4,13,4763
"2014-11-04",11,50,5,12,3185
"2014-11-05",17,79,7,21,6689
"2014-11-06",11,71,11,17,6801
"2014-11-07",13,33,8,16,1866
"2014-11-08",3,19,1,4,1139
```

In Postgres container's DB, I run this query : `plausible_db=# SELECT id, queue, worker, args, errors, inserted_at
FROM oban_jobs ORDER BY inserted_at DESC;`

And get these results : 
```
  id   |             queue              |                     worker                      |                 args                  | errors |        inserted_at
-------+--------------------------------+-------------------------------------------------+---------------------------------------+--------+----------------------------
 89457 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 16:15:00.966585
 89453 | schedule_email_reports         | Plausible.Workers.ScheduleEmailReports          | {}                                    | {}     | 2024-10-03 16:00:00.923434
 89455 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 16:00:00.923434
 89454 | site_setup_emails              | Plausible.Workers.SendSiteSetupEmails           | {}                                    | {}     | 2024-10-03 16:00:00.923434
 89456 | domain_change_transition       | Plausible.Workers.ExpireDomainChangeTransitions | {}                                    | {}     | 2024-10-03 16:00:00.923434
 89452 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 15:45:00.890689
 89451 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 15:30:00.855734
 89450 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 15:15:00.824626
 89449 | spike_notifications            | Plausible.Workers.TrafficChangeNotifier         | {}                                    | {}     | 2024-10-03 15:00:00.78466
```

> Do you mean this page?

Yes I mean this page.

> If you don't get ticks next to the filenames and the "Confirm" button lightning up, then the CSV files don't have the expected format.

I do get ticks, then click on "Confirm Import xxxxxx", it greys out and nothing happens.

![image](https://github.com/user-attachments/assets/6972470d-9ea2-43a8-aad2-d6795a0090fc)

I didn't think about checking the docker compose logs this time, my bad about that. But I would have probably posted them here anyway. So here are the logs that show up in the Plausible container right after I click on "Confirm Import xxxx"
```
16:24:36.013 [error] GenServer #PID<0.7232.0> terminating
** (File.RenameError) could not rename from "/tmp/plug-1727-wOKo/live_view_upload-1727972549-312008399860-2" to "/var/lib/plausible/plausible-imports/1/live_view_upload-1727972549-312008399860-2": cross-device link
    (elixir 1.17.1) lib/file.ex:793: File.rename!/2
    (plausible 0.0.1) lib/plausible_web/live/csv_import.ex:48: anonymous fn/3 in PlausibleWeb.Live.CSVImport.mount/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/upload_channel.ex:21: Phoenix.LiveView.UploadChannel.consume/3
    (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (plausible 0.0.1) lib/plausible_web/live/csv_import.ex:222: PlausibleWeb.Live.CSVImport.handle_event/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F_r9qtaX-hJWmndB", event: "event", payload: %{"event" => "submit-upload-form", "type" => "form", "value" => ""}, ref: "63", join_ref: "18"}
```

**Comment by ruslandoga** [comment]
Seems like the same issue as in https://github.com/plausible/analytics/issues/4638. For now, you can try using the container image linked there, and I'll make a release for v2.1.4 tomorrow.

**Comment by Aboitier** [comment]
Works like a charm. Thank you
