### ISSUE TITLE
clickhouse returns unhealthy due to healthcheck on localhost:8123

### ISSUE THREAD

**Issue by 6r33z3** [plausible/hosting#155]
Hi team. Have upgraded to `2.1.2` with simplified compose today and everything went smooth except `plausible_events_db` (clichhouse) returns unhealthy, after 1m start_period:

```sh
> docker compose up -d
[+] Running 2/2
 ✔ Container plausible-plausible_db-1         Healthy                                                                               0.5s 
 ✘ Container plausible-plausible_events_db-1  Error                                                                                 0.5s 
dependency failed to start: container plausible-plausible_events_db-1 is unhealthy
```

Upon further look into it, it seems clickhouse is having issue to ping itself at `localhost`:

https://github.com/plausible/community-edition/blob/249b22d338a746462febb880873bafcc1678a48c/compose.yml#L29

and simply replacing `localhost` with `127.0.0.1` fixed the issue without the need to expose 8123 at `ports`:

```yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1"]
```

Another observation is comparing to `2.1.1`'s compose, it would be better to note that `2.1.2`'s compose requires docker version >= v25 due to `healthcheck.start_interval` is a v25 feature, otherwise docker would return following error:

```sh
 ⠋ Container plausible-plausible_db-1  Creating                                                                                     0.0s 
can't set healthcheck.start_interval as feature require Docker Engine v25 or later
```

**Comment by ruslandoga** [comment]
👋 @6r33z3 

Thank you for the report!

I committed the suggested fix in https://github.com/plausible/community-edition/commit/86e3e4e833f7276ebcd567d58e509d9c0e607fdd

**Comment by ruslandoga** [comment]
Re `start_interval` I'll check tomorrow if we can maybe remove it.

For reference, Sentry doesn't seem to include `start_interval`: https://github.com/getsentry/self-hosted/blob/5bd6cd3710cc214b2d68858d24a7d6bcf8149d73/docker-compose.yml#L195-L205

---

**UPDATE:** removed it in https://github.com/plausible/community-edition/commit/e10a380651ba255a26e58971cc463b2c7b0d0b81
