### ISSUE TITLE
Feature Request: Add a simple, pulsing green dot to indicate when there are live visitors in the corresponding website container

### ISSUE THREAD

**Issue by IslandApps** [plausible/hosting#166]
![{C2C1E964-565E-4007-A8DF-E9ADFED13FC8}](https://github.com/user-attachments/assets/3940c780-aad9-44aa-ae18-8ef05eb600fe)
![Screenshot 2024-10-02 095615](https://github.com/user-attachments/assets/b8af2b34-7544-494b-85a1-7a2682f7b888)

**Comment by ruslandoga** [comment]
👋 @techcow2 

Please send your feature requests to https://feedback.plausible.io :)
