### ISSUE TITLE
Question - is it possible to to get Growth/Business benefits when running this locally?

### ISSUE THREAD

**Issue by profesionalaiesam** [plausible/hosting#169]
Question - is it possible to to get Growth/Business benefits when running this locally?

Such as slack notifications

**Comment by ruslandoga** [comment]
👋 @profesionalaiesam 

I don't think CE includes Slack notifications. They seem to be done via a 3rd party integration since there is no code for that in https://github.com/search?q=repo%3Aplausible%2Fanalytics%20slack&type=code

**Comment by profesionalaiesam** [comment]
So no email reports, no google analyltics import and so on right?


<img width="984" alt="image" src="https://github.com/user-attachments/assets/4750320f-dc9a-45f8-990a-e5e40a7b5179">

**Comment by ruslandoga** [comment]
CE does include email reports and Google Analytics integrations.

**Comment by profesionalaiesam** [comment]
So only thing that it is missing from the cloud solution is slack reports and premium support?

What about custom properties, stats API, funnels and so on?

**Comment by ruslandoga** [comment]
Custom properties and stats API is included in CE, but funnels are missing: https://plausible.io/blog/community-edition#a-stronger-moat-for-our-official-managed-hosting

**Comment by profesionalaiesam** [comment]
Awesome! Thanks lads!
