### ISSUE TITLE
Export data doesn't work.

### ISSUE THREAD

**Issue by thimiraonline** [plausible/hosting#175]
I'm trying to migrate my Plausible self-hosted instance to another VPS. But when I'm trying to export my existing data from my current plausible instance, it doesn't work. No any error showed.

**Comment by ruslandoga** [comment]
👋 @thimiraonline 

Could you please share your `compose.yml` file? There was a problem with rename failing when moving files from tmpfs to a volume and https://github.com/plausible/community-edition/commit/a6220d0725a1940bf712126191d1ab2fc6de628e can be used as a quick fix. And v2.1.4 has a fix that switches to cp/mv when rename fails: https://github.com/plausible/analytics/pull/4640

**Comment by thimiraonline** [comment]
> 👋 @thimiraonline
> 
> Could you please share your `compose.yml` file?

Hi @ruslandoga, Here is it

services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/ruslandoga/plausible:build-file-rename-fallback
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:

**Comment by ruslandoga** [comment]
Since you are already using `ghcr.io/ruslandoga/plausible:build-file-rename-fallback`, the problem must be in something else. Would you be able to also share `docker compose logs` from around the time that export fails? Also please try using `ghcr.io/plausible:community-edition:v2.1.4` -- in the very least it should include more logs around CSV exports/imports.

**Comment by thimiraonline** [comment]
`docker compose logs` says 


```
hosting_plausible_db_1  | 
hosting_plausible_db_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
hosting_plausible_db_1  | 
hosting_plausible_db_1  | 2024-10-21 06:55:41.654 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
hosting_plausible_db_1  | 2024-10-21 06:55:41.667 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
hosting_plausible_db_1  | 2024-10-21 06:55:41.667 UTC [1] LOG:  listening on IPv6 address "::", port 5432
hosting_plausible_db_1  | 2024-10-21 06:55:41.681 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hosting_plausible_db_1  | 2024-10-21 06:55:41.699 UTC [27] LOG:  database system was interrupted; last known up at 2024-10-21 06:50:47 UTC
hosting_plausible_db_1  | 2024-10-21 06:55:41.779 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
hosting_plausible_db_1  | 2024-10-21 06:55:41.809 UTC [27] LOG:  redo starts at 0/15227B0
hosting_plausible_db_1  | 2024-10-21 06:55:41.809 UTC [27] LOG:  invalid record length at 0/1522898: expected at least 24, got 0
hosting_plausible_db_1  | 2024-10-21 06:55:41.809 UTC [27] LOG:  redo done at 0/1522860 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
hosting_plausible_db_1  | 2024-10-21 06:55:41.826 UTC [25] LOG:  checkpoint starting: end-of-recovery immediate wait
hosting_plausible_db_1  | 2024-10-21 06:55:41.843 UTC [25] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.002 s, total=0.022 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1522898, redo lsn=0/1522898
hosting_plausible_db_1  | 2024-10-21 06:55:41.901 UTC [1] LOG:  database system is ready to accept connections
hosting_plausible_db_1  | 2024-10-21 06:57:36.845 UTC [31] FATAL:  database "plausible_db" does not exist
hosting_plausible_db_1  | 2024-10-21 06:57:36.845 UTC [32] FATAL:  database "plausible_db" does not exist
hosting_plausible_db_1  | 2024-10-21 07:00:41.940 UTC [25] LOG:  checkpoint starting: time
hosting_plausible_db_1  | 2024-10-21 07:02:14.729 UTC [25] LOG:  checkpoint complete: wrote 929 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=92.771 s, sync=0.004 s, total=92.790 s; sync files=300, longest=0.002 s, average=0.001 s; distance=4309 kB, estimate=4309 kB; lsn=0/1957DF8, redo lsn=0/1957DC0
hosting_plausible_db_1  | 
hosting_plausible_db_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
hosting_plausible_db_1  | 
hosting_plausible_db_1  | 2024-10-21 07:24:33.616 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
hosting_plausible_db_1  | 2024-10-21 07:24:33.617 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
hosting_plausible_db_1  | 2024-10-21 07:24:33.617 UTC [1] LOG:  listening on IPv6 address "::", port 5432
hosting_plausible_db_1  | 2024-10-21 07:24:33.624 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hosting_plausible_db_1  | 2024-10-21 07:24:33.635 UTC [28] LOG:  database system was shut down at 2024-10-21 07:23:32 UTC
hosting_plausible_db_1  | 2024-10-21 07:24:33.665 UTC [1] LOG:  database system is ready to accept connections
hosting_plausible_db_1  | 2024-10-21 07:29:33.722 UTC [26] LOG:  checkpoint starting: time
hosting_plausible_db_1  | 2024-10-21 07:29:33.803 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.028 s, sync=0.012 s, total=0.083 s; sync files=2, longest=0.006 s, average=0.006 s; distance=0 kB, estimate=0 kB; lsn=0/1957F90, redo lsn=0/1957F58
hosting_plausible_events_db_1  | ClickHouse Database directory appears to contain a database; Skipping initialization
hosting_plausible_events_db_1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
hosting_plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
hosting_plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
hosting_plausible_events_db_1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
hosting_plausible_events_db_1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
hosting_plausible_events_db_1  | 2024.10.21 10:05:52.669826 [ 1 ] {} <Warning> Context: Linux is not using a fast clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
hosting_plausible_events_db_1  | 2024.10.21 10:05:52.674343 [ 1 ] {} <Warning> Context: Linux threads max count is too low. Check /proc/sys/kernel/threads-max
hosting_plausible_events_db_1  | 2024.10.21 10:05:52.674533 [ 1 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
hosting_plausible_events_db_1  | 2024.10.21 10:05:52.674616 [ 1 ] {} <Warning> Context: Available memory at server startup is too low (2GiB).
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.012438 [ 1 ] {} <Warning> Context: Maximum number of threads is lower than 30000. There could be problems with handling a lot of simultaneous queries.
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.080668 [ 1 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
hosting_plausible_events_db_1  | 
hosting_plausible_events_db_1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
hosting_plausible_events_db_1  | 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
hosting_plausible_events_db_1  | 2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cce452e
hosting_plausible_events_db_1  | 3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd562bd
hosting_plausible_events_db_1  | 4. Poco::Util::Application::run() @ 0x0000000014ca8606
hosting_plausible_events_db_1  | 5. DB::Server::run() @ 0x000000000cd46671
hosting_plausible_events_db_1  | 6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
hosting_plausible_events_db_1  | 7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
hosting_plausible_events_db_1  | 8. main @ 0x0000000007651578
hosting_plausible_events_db_1  | 9. ? @ 0x0000776c3f468083
hosting_plausible_events_db_1  | 10. _start @ 0x0000000005dee46e
hosting_plausible_events_db_1  |  (version 24.3.3.102 (official build))
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.188166 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.254746 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.255297 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.255939 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting_plausible_events_db_1  | 2024.10.21 10:05:56.257173 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.3.3.102 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

**Comment by ruslandoga** [comment]
Doesn't seem like there are any logs from `plausible` container itself, could you try `docker compose logs plausible`?

**Comment by thimiraonline** [comment]
> docker compose logs plausible

There's nothing in there 🥲

![Screenshot 2024-10-21 at 3 57 22 PM](https://github.com/user-attachments/assets/8cb6afe1-c781-458e-b533-60d6bfb229e9)

**Comment by ruslandoga** [comment]
Hm, strange. I would've expected at least startup / migration logs.

Could you try using `ghcr.io/plausible:community-edition:v2.1.4` for the `plausible` image?

Also what does `docker compose ps` return right now?

**Comment by thimiraonline** [comment]
> Could you try using `ghcr.io/plausible:community-edition:v2.1.4` for the `plausible` image?

I just changed it and ran the docker with ghcr.io/plausible/community-edition:v2.1.4


> Also what does `docker compose ps` return right now?

![Screenshot 2024-10-21 at 4 03 01 PM](https://github.com/user-attachments/assets/182b7355-bcc5-4d96-aadb-d890fc8c1842)

**Comment by ruslandoga** [comment]
Seems like `plausible` container is not running, that's also probably why the logs are missing. What was the output of `docker compose up -d`? Are there any stoped containers in `docker compose ps -a`? If there are, you can inspect them with `docker inspect` to find out the exit reason.

**Comment by thimiraonline** [comment]
Now it doesn't let me to stop 2 containers. it says as follows.

![Screenshot 2024-10-21 at 4 07 03 PM](https://github.com/user-attachments/assets/f76f146f-9aed-4c4b-8fc6-c9ec175655d9)

**Comment by ruslandoga** [comment]
Permission errors might be caused by `sudo`.

**Comment by thimiraonline** [comment]
> Permission errors might be caused by `sudo`.

without sudo It doesn't let me to run the command.

![Screenshot 2024-10-21 at 4 09 15 PM](https://github.com/user-attachments/assets/b7789e93-7a97-47c8-966d-c3b50165026f)

**Comment by ruslandoga** [comment]
Please see https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue and https://docs.docker.com/engine/install/linux-postinstall/

There is a log of information on this issue on the internet. Once it is resolved, we would be able to get back to the exports issue. This particular problem is not related to Plausible so you would need to solve it on your own.

**Comment by thimiraonline** [comment]
> Please see https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue
> 
> There is a log of information on this on the internet. Once it is resolved, we would be able to get back to the exports issue. This particular problem is not related to Plausible so you would need to solve it on your own.

Is there a way to clone my existing VPS docker to another one?

**Comment by ruslandoga** [comment]
Do you mean the executables? Or volumes? It's possible to do the latter with rsync or some similar tool.

**Comment by thimiraonline** [comment]
> Do you mean the executables? Or volumes? It's possible to do the latter with rsync or some similar tool.

I want to move the existing instance to another new VPS

**Comment by thimiraonline** [comment]
Plausible Errors were fixed. Now showing like this.

![Screenshot 2024-10-21 at 5 36 35 PM](https://github.com/user-attachments/assets/48cca7b8-a146-477a-a25a-5e705a9762d4)

**Comment by ruslandoga** [comment]
Great! Now please try to perform an export and if it fails, please post the logs here. Note that the logs need to come from the instance doing the export, which is probably your existing instance.

**Comment by thimiraonline** [comment]
Still the export option doesn't work. I just tried with ghcr.io/ruslandoga/plausible:build-file-rename-fallback again. 

![Screenshot 2024-10-21 at 5 53 34 PM](https://github.com/user-attachments/assets/024d796e-9bb3-42d0-a22f-6fd1e419a43d)

**Comment by ruslandoga** [comment]
Please check oban_jobs table for errors. In pre-v2.1.4 the errors from background jobs (where exports happen) weren't logged.

```sh
docker compose exec plausible_db psql -h localhost -U postgres -d plausible_db
```
```sql
select * from oban_jobs;
```

**Comment by thimiraonline** [comment]
> Please check oban_jobs table for errors. In pre-v2.1.4 the errors from background jobs (where exports happen) weren't logged.

Nothing is in there. Last record was in October 05, 2024. and it is about scheduling email report.

**Comment by thimiraonline** [comment]
Is this a problem related import export?

<img width="1141" alt="Screenshot 2024-10-21 at 8 46 48 PM" src="https://github.com/user-attachments/assets/6590af71-140c-477c-9129-20b5d2af2d12">

**Comment by ruslandoga** [comment]
It's more general. It might affect exports as well. For example, clicking a button to start exports would be no-op. You should check if your reverse proxy is allowing websocket connections.

**Comment by thimiraonline** [comment]
> It's more general. It might affect exports as well. For example, clicking a button to start exports would be no-op. You should check if your reverse proxy is allowing websocket connections.

I modified nginx as following, but still not yet issue fixed.

```
server {
    server_name test.androidwedakarayo.com;

    # Proxy all traffic to backend
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # For WebSocket keep-alive (optional, but may help)
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # WebSocket specific location (optional)
    location /live/websocket {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket specific timeout settings
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/test.androidwedakarayo.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/test.androidwedakarayo.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# Redirect HTTP to HTTPS
server {
    if ($host = test.androidwedakarayo.com) {
        return 301 https://$host$request_uri;
    }

    server_name test.androidwedakarayo.com;
    listen 80;
    return 404;
}
```

**Comment by thimiraonline** [comment]
> It's more general. It might affect exports as well. For example, clicking a button to start exports would be no-op. You should check if your reverse proxy is allowing websocket connections.

Is there any way to help me out if I can give you the server access. I have a seperate server for plausible.

**Comment by ruslandoga** [comment]
Note that you need to restart nginx for the new configuration to take action: https://github.com/plausible/community-edition/wiki/reverse-proxy#nginx

**Comment by thimiraonline** [comment]
I got the issue with exporting data. Websocket was not connected because I have turned on cloudflare proxy in DNS A record. Once I disabled it, export worked after 2 hours. CE v2.1.4.

**Comment by ruslandoga** [comment]
Glad you got it working!
