### ISSUE TITLE
API to add sites

### ISSUE THREAD

**Issue by Leapje** [plausible/hosting#179]
Since the last update (2.1.4) it is no longer possible to add sites through the API.
Is this a bug or is this removed intentionally?

Thanks for the great product by the way!

**Comment by ruslandoga** [comment]
👋 @Leapje 

This functionality has been removed intentionally in [v2.1.0](https://github.com/plausible/analytics/discussions/4125) (CE): https://plausible.io/blog/community-edition#a-stronger-moat-for-our-official-managed-hosting
