### ISSUE TITLE
being sent back to /settings when trying to open stats

### ISSUE THREAD

**Issue by RaZer0r** [plausible/hosting#18]
Hey guys,

I've been running the docker version for a little while now, but one of the accounts is getting an error when he tries to access his domain stats.
Login works fine, but when clicking on a domain, he is being redirected to /settings, not the domain.

In the mean time the docker container is throwing an error:

`plausible_1            | Request: GET /kwacha.webflow.io
plausible_1            | ** (exit) an exception was raised:
plausible_1            |     ** (Plug.Conn.AlreadySentError) the response was already sent
plausible_1            |         (plug 1.10.1) lib/plug/conn.ex:1535: Plug.Conn.put_session/3
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:21: PlausibleWeb.StatsController.stats/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.action/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.phoenix_controller_pipeline/2
plausible_1            |         (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
plausible_1            |         (plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Router.call/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint."call (overridable 3)"/2
plausible_1            | 12:34:33.670 request_id=FksO5iElfq0pwW4AAAFF [warn] Failed to send Sentry event.Cannot send Sentry event because of invalid DSN
plausible_1            | 12:34:33.676 [error] #PID<0.4461.0> running PlausibleWeb.Endpoint (connection #PID<0.4460.0>, stream id 1) terminated
plausible_1            | Server: stats.vejnoe.dk:80 (http)
plausible_1            | Request: GET /kwacha.webflow.io
plausible_1            | ** (exit) an exception was raised:
plausible_1            |     ** (Plug.Conn.AlreadySentError) the response was already sent
plausible_1            |         (plug 1.10.1) lib/plug/conn.ex:1535: Plug.Conn.put_session/3
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:21: PlausibleWeb.StatsController.stats/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.action/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.phoenix_controller_pipeline/2
plausible_1            |         (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
plausible_1            |         (plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Router.call/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint."call (overridable 3)"/2`

**Comment by RaZer0r** [comment]
tried running the dev tag too, but that did not make a difference.

**Comment by ukutaht** [comment]
Unfortunately we don't have a clean separation between some behaviour we need in the cloud that makes no sense for self-hosters.

This happens because new users get a 30-day trial when signing up. If they don't have a subscription once the trial is over, they are locked out of their stats.

You can fix it by logging into your postgres database, finding their record from the `users` table and setting the `trial_expiry_date` to somewhere very far in the future.

We also need a way to prevent this from happening in the future.

**Comment by jimmybrancaccio** [comment]
Oh man, this just happened to me. I had my admin user which was created when I originally set this up, but I also created an account for myself and the expire date was `2020-12-11` so I was wondering what the heck was going on. Even having had some information like, YOUR ACCOUNT IS EXPIRED, being shown on the Setting page would have made troubleshooting this 110% less sucky.

Ideally 2 things could be done to improve this:

1. Just set the expiry date for all new users in self-hosted installation to some date in the far future.
2. Add an alert box on the Settings page letting the user know their subscription is expired.

**Comment by ruslandoga** [comment]
Closing as this should be resolved in the recent versions
