### ISSUE TITLE
Does Stats API v2 supported in CE

### ISSUE THREAD

**Issue by dookimm** [plausible/hosting#183]
While I tested stats api v2 in my self host instance, it return 404 response code. v1 works.

**Comment by ruslandoga** [comment]
👋 @dookimm 

AFAIK it's still in beta in Plausible Cloud. So it's not in CE officially, although there is some code from APIv2 in there.

**Comment by dookimm** [comment]
@ruslandoga got it. TYFYI

**Comment by grssnbchr** [comment]
Is there any news regarding this? Is V2 available for the CE? Some documentation, anything?

**Comment by dookimm** [comment]
> Is there any news regarding this? Is V2 available for the CE? Some documentation, anything?

AFAIK V2 api is already available fro the CE v3+

**Comment by grssnbchr** [comment]
I am running v3.0.1 and the endpoint `https://{customdomain}/api/v2/query` returns a 404. 
If Stats V2 were available, that would not be the case, right?

My bad: I mistakingly sent a GET request. With POST it indeed is available. 
Thank you!
PS. Would have expected a 405 Method Not Allowed.. but these are details ;-)
