### ISSUE TITLE
Can't run the plausible container - container is unhealthy

### ISSUE THREAD

**Issue by filiprojek** [plausible/hosting#184]
Hi, I'm trying to run plausible-ce v2.1.4 by following the [docs](https://github.com/plausible/community-edition/tree/v2.1.3#quick-start). I want to serve plausible using reverse proxy as described [here](https://github.com/plausible/community-edition/wiki/reverse-proxy).
When i created the `.env` and `compose.override.yml` files, I've tried to run the `docker-compose up` command, but that failed.
I think i did nothing wrong. I couldn't find any more related logs to this issue.

I'm using `Alpine Linux v3.16` and `Docker v20.10.20` .  
I was using plausible v2.0 with the old image from [Docker Hub](https://hub.docker.com/r/plausible/analytics) without any issues on the same domain.

**terminal output**
```sh
[fr@s3 analytics][v2.1.4]$ docker-compose up
Creating network "analytics_default" with the default driver
Creating analytics_plausible_events_db_1 ... done
Creating analytics_plausible_db_1        ... done

ERROR: for plausible  Container "12df29d405b5" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
**compose.override.yml**
```yml
services:
  plausible:
    ports:
      - 5120:80
```
**.env**
```.env
BASE_URL=https://subdomain.mydomain.com
SECRET_KEY_BASE=somekey
HTTP_PORT=5120
```

**Comment by ruslandoga** [comment]
👋 @filiprojek 

Try `docker compose up` instead.

`docker-compose` is the old CLI and AFAIK has been deprecated since ~2 years ago. Maybe it doesn't support the healthchecks options defined in `compose.yml`

**Comment by ruslandoga** [comment]
> Hi, I'm trying to run plausible-ce v2.1.4 by following the [docs](https://github.com/plausible/community-edition/tree/v2.1.3#quick-start).

This is probably not relevant to the problem, but the link leads to v2.1.3 version docs.

**Comment by filiprojek** [comment]
> 👋 @filiprojek
> 
> Try `docker compose up` instead.
> 
> `docker-compose` is the old CLI and AFAIK has been deprecated since ~2 years ago. Maybe it doesn't support the healthchecks options defined in `compose.yml`

I'm using older version of Alpine, I do not have newer docker version. I will try to upgrade. Thanks

**Comment by filiprojek** [comment]
You were right, I was using an old version of docker. Thanks for the help!
