### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by Aboitier** [plausible/hosting#186]
Hello there,

I am trying to add new users to our Plausible. 

When I press the button "Send Invite", it lags for about 20 seconds then confirms with a pop-in the top-right corner "Success! xxxxxx@yyyy.zz has been invited to xxx.yyyy.zzz as a viewer" but no emails is received. 

Nothing in the bytemark/smtp container logs and this mention : "request_id=GAo_VCkE9pazFiUB4_ri [error] Failed to send e-mail" in the plausible logs.

Any hint about what's the problem here and would you have an email bypass to still add the new member without going through email ?

Thanks a lot

**Comment by ruslandoga** [comment]
👋 

You can try sending an email manually, the error there would provide more information. You can also connect Sentry.

Please see https://github.com/plausible/analytics/discussions/4844

**Comment by ruslandoga** [comment]
Note that bytemark/smtp is no longer used in the default configuration.

**Comment by Aboitier** [comment]
Thanks for your answer.

I successfully sent an email manually. 

Do you have any material to share to connect Sentry ? 
I saw on other issues that you were about to release a new version with extended logging about mail errors, do you have a test image I can use to not have to connect Sentry ?

**Comment by ruslandoga** [comment]
https://github.com/plausible/analytics/pull/4846 is still WIP. I'll try to finish it up tomorrow or during the weekend and reply with a container image for testing here.

**Comment by ruslandoga** [comment]
Re: `SENTRY_DSN`, I replied at https://github.com/plausible/analytics/discussions/4844#discussioncomment-11407947

It might be a good idea to add it to the default `compose.yml` 🤔
