### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by bgruening** [plausible/hosting#188]
It would be nice to add a license file to this repo.

**Comment by ruslandoga** [comment]
👋 @bgruening 

It would be nice indeed!

---

@ukutaht 👋 

I wonder if you could help in picking the right one (AGPL?) from https://github.com/plausible/community-edition/community/license/new? I'll then backport it to the earlier releases.

**Comment by ukutaht** [comment]
👋 Hello :)

Let's go with MIT on this repo. AGPL applies to the main product but I think for this kind of configuration code we can use a more standard and permissive license.

**Comment by ruslandoga** [comment]
Done: https://github.com/plausible/community-edition/commit/dcf3ad94ae69d8984038db3bf2d4468aac58ba73

---

@bgruening thank you for bringing it up!
