### ISSUE TITLE
My Plausible is just reloading repeatedly(the website)

### ISSUE THREAD

**Issue by Bansku-Dansku** [plausible/hosting#189]
Hi!

I was trying to install Plausible on my vps and It went great until I needed to access the website. The website just reloads repeatedly. Im currently running Plausible behind a Nginx reverse proxy. 

The address where I run my Plausible: http://stats.axsoter.com/

**Comment by ruslandoga** [comment]
👋 @Bansku-Dansku 

The TLS certificate for https://stats.axsoter.com/ domain is for `track.axsoter.com` so you might have misconfigured something. And judging by `secure;` being set in the cookie, your [$BASE_URL](https://github.com/plausible/community-edition/wiki/configuration#base_url) has HTTPS scheme, hence the redirect.

You can either change the domain name to `track.axsoter.com` or issue and use a certificate for `stats.axsoter.com` :)
