### ISSUE TITLE
No breakdown by event props possible

### ISSUE THREAD

**Issue by bjoernbg** [plausible/hosting#19]
Thanks for the nice work with Plausible! We really like the clean approach.

We are trying to use the hosted version of Plausible but ran into a few issues. Setup itself was relatively easy with Docker, but integrating it with our website caused some issues. I'm breaking these down into seperate issues.

Following the documentation here: https://docs.plausible.io/custom-event-goals/
we set up event tracking and the events show up ok in the analytics UI. However, all props seem to get lost in the process. I  looked at the tracking request itself and saw that the JS didn't even include the `props` object! I then looked at the snippet you are using on plausible.io and saw that there are substantial differences. Adapting your plausible.io script to my local installation was easy and now the props object is sent to the server (as well as referers, btw., that also didnt work before).

The events are shown on the analytics page, but there is no way to drill down like you show in your documentation. Is there some switch that i have to turn for this to work?

**Comment by ukutaht** [comment]
Hi @bjoernbg 👋

We haven't cut a release in November so some new features are missing from the self-hosted release. You can see which features unreleased in our changelog: https://github.com/plausible/analytics/blob/master/CHANGELOG.md

You can run from the `dev` docker tag to get access to the latest features. However, you can expect that tag to be less stable than released versions.

I'm open to suggestions on how to communicate this better or how to change our release process but I'll close this issue for now. Breakdown by props is an unreleased feature as it stands.

**Comment by bjoernbg** [comment]
@ukutaht Thanks for this update. It's a bit confusing from the docs but I get it!

**Comment by ukutaht** [comment]
@bjoernbg No worries. I'll update the docs to reflect this more clearly :)

**Comment by hazem3500** [comment]
Hey, I've used the `dev` docker tag but the `plausible.js` script still doesn't take the `props` property for custom events. Does that mean that it's still not released even on the `dev` version?

here is the `plausible.js` file if it will be of any use
```js
!(function (i, r) {
    'use strict';
    var s = i.location,
        o = i.document,
        e = o.querySelector('[src*="' + r + '"]'),
        l = e && e.getAttribute('data-domain'),
        t = !1;
    function n(e, t) {
        if (
            /^localhost$|^127(?:\.[0-9]+){0,2}\.[0-9]+$|^(?:0*\:)*?:?0*1$/.test(
                s.hostname
            ) ||
            'file:' === s.protocol
        )
            return console.warn('Ignoring event on localhost');
        var n = {};
        (n.n = e),
            (n.u = s.href),
            (n.d = l),
            (n.r = o.referrer || null),
            (n.w = i.innerWidth);
        var a = new XMLHttpRequest();
        a.open('POST', r + '/api/event', !0),
            a.setRequestHeader('Content-Type', 'text/plain'),
            a.send(JSON.stringify(n)),
            (a.onreadystatechange = function () {
                4 == a.readyState && t && t.callback && t.callback();
            });
    }
    function a() {
        n('pageview');
    }
    try {
        var c,
            p = i.history;
        p.pushState &&
            ((c = p.pushState),
            (p.pushState = function () {
                c.apply(this, arguments), a();
            }),
            i.addEventListener('popstate', a));
        var u = (i.plausible && i.plausible.q) || [];
        i.plausible = n;
        for (var d = 0; d < u.length; d++) n.apply(this, u[d]);
        'prerender' === o.visibilityState
            ? o.addEventListener('visibilitychange', function () {
                  t || 'visible' !== o.visibilityState || ((t = !0), a());
              })
            : a();
    } catch (e) {
        new Image().src =
            r + '/api/error?message=' + encodeURIComponent(e.message);
    }
})(window, 'https://my-analytics-domain.com');

```
