### ISSUE TITLE
Data Import from Google Analytics Stuck on Loading

### ISSUE THREAD

**Issue by adrianmihalko** [plausible/hosting#199]
I successfully set up the integration with Google Analytics following the guide provided. However, when I attempt to import data, the import process gets stuck on "loading" and does not complete.

**Steps to Reproduce:**

Follow the setup guide to integrate Google Analytics.
Navigate to the data import section.
Click on the "Import" button.

**Expected Behavior:**

The data import process should complete successfully and display the imported data.

Actual Behavior:

The import process stays in a "loading" state indefinitely, and no data is imported.

<img width="1153" alt="Screenshot 2024-12-06 at 23 04 34" src="https://github.com/user-attachments/assets/d002d448-6a7f-494c-9335-a9fec19ab808">

In logs I don't see any unusual:

```
madrian@:~/docker/plausible-ce$ sudo docker logs --follow 08bf694c5b37
------------------------------------------------------------------------------
Loading plausible..
Starting dependencies..
Starting repos..
Plausible.Repo database already exists
Plausible.IngestRepo database already exists
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
Loading plausible..
Starting dependencies..
Starting repos..
Plausible.Repo database already exists
Plausible.IngestRepo database already exists
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
Loading plausible..
Starting dependencies..
Starting repos..
Plausible.Repo database already exists
Plausible.IngestRepo database already exists
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
```

**Comment by ruslandoga** [comment]
👋 @adrianmihalko 

What container image are you using? The latest one, `v2.1.4` should have extra error logging for background jobs so it might help debug this issue. If you are already on `v2.1.4` then please share all logs (including ClickHouse) and check if any of the containers are being OOM-killed:

```console
$ cd plausible-ce
$ docker compose logs
$ docker compose ps -a
```

If that also doesn't provide any insight, try checking `oban_jobs` table (that's where our background jobs are stored) for errors:

```console
$ docker compose exec plausible_db psql -d plausible_db -U postgres -h localhost
```
```sql
select * from oban_jobs;
```

**Comment by adrianmihalko** [comment]
Hi @ruslandoga,

Sorry for not closing the issue earlier—I resolved it yesterday. The problem was that I was running Plausible on a VPS with only 1GB of RAM. As you mentioned, the import process likely crashed and was OOM-killed in the background.

After upgrading the memory to 2GB, the process completed successfully. It wasn't immediately obvious because there was no indication of this in the logs.

Thanks for your help!
