### ISSUE TITLE
plausible.js script broken

### ISSUE THREAD

**Issue by bjoernbg** [plausible/hosting#20]
Thanks for the nice work with Plausible! We really like the clean approach.

We are trying to use the hosted version of Plausible but ran into a few issues. Setup itself was relatively easy with Docker, but integrating it with our website caused some issues. I'm breaking these down into seperate issues.

We have several issues with the `plausible.js` script.

1. Initially the admin UI gave a link to `http://ourserver/js/plausible.js`. This didn't work because the `BASE_URL` wasn't respected in the script, it was hardcoded to `localhost`.
2. Using the custom domain option in the admin UI gave us a different snippet path: `http://ourserver/js/index.js`. This doesn't exist at all.

**Comment by KevinCooper** [comment]
I ran into the same issue.

Setting the BASE_URL in the `plausible-conf.env` resulted in the `Add javascript snippet` producing the correct URL.  However, the `plausible.js` file seems to use a hardcoded `(window,"http://localhost:8000");` and does not properly send the analytics data to the BASE_URL  identified.

**Comment by mannp** [comment]
Had everything working great but not exactly sure when, but my plausible is completely borked.

Same issues as here and /js/index.js doesn't exist any more.

**Comment by ukutaht** [comment]
Could you copy the `BASE_URL` from your configuration for debugging? I just tested the following:
```
BASE_URL=https://selfhost.plausible.io
```

I can access the script at `/js/plausible.js` and it sends data to `https://selfhost.plausible.io/api/event`. All working as intended.

**Comment by bjoernbg** [comment]
There are two issues here: The admin panel gives me this URL (anonymized):
`<script async defer data-domain="mydomain.de" src="https://analytics.mydomain.de/js/index.js"></script>`
but that url does not exist.

Before I switched on "Custom Domain" the script tag pointed to this location: `https://analytics.ergosign.de/js/plausible.js` which – despite having set the `BASE_URL` did include `…}}(window,"http://localhost:8000");` at the end. Since it's not very complicated I copied the script, changed the necessary bits for it to work and everything was fine.

For a different reason (drill-down into goals) I switched from the `:latest` tag to `:dev` – I just rechecked `plausible.js` and it seems to be fixed!
Maybe it's time to create a new release?

**Comment by mabasic** [comment]
If you are using custom domain feature inside the settings panel, that does not work for self hosted plausible atm.

**Comment by ukutaht** [comment]
@bjoernbg Thanks for cheking. I will cut a release soon.

**Comment by bjoernbg** [comment]
> If you are using custom domain feature inside the settings panel, that does not work for self hosted plausible atm. Needs to be implemented.

Yeah, that confused me a bit, as well. Doesn't seem necessary for the self-hosted version anyway – I only tried it because it didn't work (because `plausible.js` pointed to `localhost`) and didn't bother to turn it off again.

Anyway, we really like Plausible so far. It has some way to go but it's already a good replacement for Google Analytics.

**Comment by iwaffles** [comment]
I've tried the dev tag of plausible as well as latest,  and with both I'm seeing that index.js doesn't exist, and plausible.js is always returning `http://localhost:8000`

**Comment by iwaffles** [comment]
Ok was able to get it to work using `/js/plausible.js` on the `:dev` docker tag, though /js/index.js still throws a 404.

By removing the custom domain setting in the UI, it seems to now be sending events to the right self hosted URL (from `BASE_URL`) rather than `localhost:8000`.

**Comment by vHanda** [comment]
I just tried it out and I didn't encounter this issue, so maybe this can be closed :)

**Comment by metmarkosaric** [comment]
thanks @vHanda!
