### ISSUE TITLE
Can't access using IP it always redirect to the base IP

### ISSUE THREAD

**Issue by bobokaha** [plausible/hosting#200]
Hello, when I try to access my Plausible panel using the IP address, it always redirects to the base IP. The issue arises when I attempt to set up a reverse proxy with another server—it still redirects to the IP of the main server.

Specifically, when I visit IP:8000, it redirects to the base IP.

Only the host domain works correctly, but it can’t proxy it using Nginx.

Is there any way to solve this?

**Comment by ruslandoga** [comment]
👋 @bobokaha 

Sorry, I'm not sure I understand the problem. What's a base IP? Could you provide examples of what you expect and what happens instead? Also, it would be helpful to know how you've configured your instance.
