### ISSUE TITLE
Warning about Postgres ports being exposed

### ISSUE THREAD

**Issue by RichGuk** [plausible/hosting#4]
There should be some documentation or warning about the Postgres ports being exposed (and maybe suggest changing password the postgres password).

I brought the docker compose up to test and got caught out by this issue https://github.com/docker-library/postgres/issues/664. Docker opens up the ports within iptables and combine this with the weak default password. I'm sure others might make the same configuration mistake.

The ports don't actually need to be exposed in the compose file as the other containers use the docker network?

**Comment by ukutaht** [comment]
Thanks for reporting the issue. I actually ran into this issue myself over the weekend: https://twitter.com/ukutaht/status/1315280850922156033

How can we fix the Dockerfile so the containers can talk to each other over the local network but the only port exposed to the outside world is `80` or whatever you configure as the webserver's exposed port?

**Comment by ukutaht** [comment]
Based on quick look online it seems like we should change port mappings to include localhost `127.0.0.1:5432` and define the exposed port on `0.0.0.0:80`

**Comment by RichGuk** [comment]
Yeah, that would work; we could change it to bind to loopback ip instead.

However, plausible_db and plausible_events_db don't actually need the ports exposed. Docker compose will create isolated network for the file, and you're using [internal network/hostname in the config](https://github.com/plausible/analytics/blob/master/config/releases.exs#L16 ).

If you wanted to access postgres directly you could run:

```
docker-compose exec plausible_db psql -Upostgres
```

**Comment by ukutaht** [comment]
I've removed the port exposure from our default docker-compose.yml file in https://github.com/plausible/hosting/commit/891914e9a110e26b198f0764635b373be571468f

Thanks for reporting!
