### ISSUE TITLE
Please make use of releases

### ISSUE THREAD

**Issue by kees-closed** [plausible/hosting#41]
Please make use of releases, that will make it easier to track for new releases and setup Ansible to act on that. Checking out the main branch, while config files need to be changed in there, creates issues with git. A git repo cannot pull in new changes with local changes. When using releases I can receive a notification of a new release, update the variable of that release tag, run a test and deploy it. Thanks for considering.

**Comment by ukutaht** [comment]
We do use releases on the main https://github.com/plausible/analytics repo. You can subscribe to that repo to get notified of new releases. This one is more of an example/reference docker-compose hosting setup, not a deployable artefact.

I suppose it could be a deployable artefact on it's own but then we would have to figure out how to accommodate config and docker-compose customizations.

**Comment by kees-closed** [comment]
Thanks for clarifying. I've subscribed on that repo, then at least I know that there is a release. But an automated workflow would be preferred of course. I also do this for the Jitsi docker-compose repo.
