### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by kees-closed** [plausible/hosting#48]
Please consider using release tags, then people can get notified when a new release is ready and update in time.

**Comment by ukutaht** [comment]
Please subscribe to https://github.com/plausible/analytics

**Comment by kees-closed** [comment]
But I suppose the container often also has the needed updates? It's not just the application it ships, it ships a whole environment which needs to be maintained as well. That release is about 6 months old. Whatever is running in that container needs a rebuild from time to time, correct? That's why I was assuming some kind of container tag I could track. Then I know when to pull in the latest one.

**Comment by ukutaht** [comment]
We release every 6 months or so, with notes on how to upgrade etc. No need to follow anything else

**Comment by kees-closed** [comment]
What I mean is that the container is a Linux environment, it's not just the Plausible software, and just like any Linux environment you get regular security updates. It's not uncommon to rebuild containers every week or at least when there are security updates available (not just for the software you're packaging and distributing).
