### ISSUE TITLE
Error since last update at boot

### ISSUE THREAD

**Issue by bilyboy785** [plausible/hosting#59]
Plausible Self Hosted : Docker
Docker Version : Docker version 20.10.21, build baeda1f
Host informations : 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Compose version : 3.3
Docker tag : latest

Error : 

```
ERROR! Config provider Config.Reader failed with:
** (Jason.DecodeError) unexpected byte at position 38: 0x70 ("p")
    lib/jason.ex:92: Jason.decode!/2
    (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17.1) erl_eval.erl:446: :erl_eval.expr/5
    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
    (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
    (elixir 1.13.4) lib/config/reader.ex:92: Config.Reader.read!/2
```

I use watchtower to auto pull and recreate, but i don't see any tags on the Docker Hub for plausible.

**Comment by zigazajc007** [comment]
Hello,

I have the same issue, how did you fixed it?

**Comment by zigazajc007** [comment]
Adding:
```env
BUILD_METADATA={}
``` 
to plausible-conf.env solve this issue.
