### ISSUE TITLE
Fail to start plausible service: driver failed programming external connectivity

### ISSUE THREAD

**Issue by zeograd** [plausible/hosting#6]
When launching the `docker-compose up --detach` command on current head 09fb07ef6015583fbc9e6b7e2b3723de666ab5a5 I end up with an error related to ports.

```
$ docker-compose up --detach
Removing hosting_plausible_1
Starting hosting_mail_1                ... done
Starting hosting_plausible_db_1        ... done
Starting hosting_plausible_events_db_1 ... done
Starting 08bc5c668828_hosting_plausible_1 ... error

ERROR: for 08bc5c668828_hosting_plausible_1  Cannot start service plausible: driver failed programming external connectivity on endpoint 08bc5c668828_hosting_plausible_1 (35456500b7f62f11d746ef8e6ff73a321e38abf7342a3904d0b83631f6f0c701): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for plausible  Cannot start service plausible: driver failed programming external connectivity on endpoint 08bc5c668828_hosting_plausible_1 (35456500b7f62f11d746ef8e6ff73a321e38abf7342a3904d0b83631f6f0c701): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```

I feared it was due to my host port 8000 being in use first (preventing the guest 80 mapping to it) but even freeing my host port 8000 didn't help.
The error code being about port 80, I assume it's an issue on guest side but I'm not knowledgeable enough in docker to figure this error out.

Thanks in advance for your help.

**Comment by MoryCorp** [comment]
Could you try a "docker ps" to list all running containers to check if there's one already running on port 80

**Comment by zeograd** [comment]
It looks like there is no other container claiming this port. Actually, none before, and after running the docker-compose command, only the db and mail containers from plausible itself.
I'm using docker `Docker version 18.09.1, build 4c52b90` if that matters.
```
olivier@nausicaa:~/work/hosting$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

olivier@nausicaa:~/work/hosting$ docker-compose up --detach
Creating hosting_plausible_events_db_1 ... done
Creating hosting_mail_1                ... done
Creating hosting_plausible_db_1        ... done
Recreating 08bc5c668828_hosting_plausible_1 ... error

ERROR: for 08bc5c668828_hosting_plausible_1  Cannot start service plausible: driver failed programming external connectivity on endpoint hosting_plausible_1 (d414e0f9b123cde5b10a4cf62ae0ef69b703aca2faa8236783ce1eeffa89867d): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for plausible  Cannot start service plausible: driver failed programming external connectivity on endpoint hosting_plausible_1 (d414e0f9b123cde5b10a4cf62ae0ef69b703aca2faa8236783ce1eeffa89867d): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

olivier@nausicaa:~/work/hosting$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
47671f54c99d        bytemark/smtp       "docker-entrypoint.s…"   12 seconds ago      Up 7 seconds        25/tcp              hosting_mail_1
751d0462d5c7        postgres:12         "docker-entrypoint.s…"   12 seconds ago      Up 7 seconds        5432/tcp            hosting_plausible_db_1
```

**Comment by MoryCorp** [comment]
Could you try something like : ``sudo lsof -i -P -n | grep 80``
Should list all services using port "80"

**Comment by zeograd** [comment]
I do have apache running on my host on port 80 (intended to be configured as reverse proxy in a later step)
```
olivier@nausicaa:~/work/hosting$ sudo lsof -i :80
COMMAND   PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
...
apache2    2307           root    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
apache2    5834       www-data    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
apache2    5842       www-data    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
apache2    5843       www-data    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
apache2    5845       www-data    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
apache2    5846       www-data    4u  IPv6   35010      0t0  TCP *:80 (LISTEN)
...```

**Comment by MoryCorp** [comment]
I'm not sure I understand what you're trying to do with Apache but if you want to run multiple services on port 80, I created this repository to run Plausible.io with Traefik 2 as a reverse proxy.

https://github.com/MoryCorp/Plausible.io-behind-Traefik2

Would this help ?

**Comment by zeograd** [comment]
So it's most probably a misunderstanding on my side regarding the port usage of this docker setup.
I'll dig into this other repo and will close this issue as of now.
Thanks for having taken time to help me and sorry for the inconvenience.

**Comment by MoryCorp** [comment]
Plausible is running on port '8000' but the default docker-compose will bind port "8000" to "80"
If you want to run plausible on another port, just to see if it works for example, you could change line '31' of the docker-compose.yml from :

    ports:
      - 80:8000

to : 

    ports:
      - 8000:8000

Then run ``docker-compose up -d``
Plausible should be available at : youdomain.com:8000

**Comment by zeograd** [comment]
Yes, that did the trick and I wrongly assumed that was the default behaviour.
Thanks a lot.
