### ISSUE TITLE
Self-hosted JS snippet has no port 8000 in URL

### ISSUE THREAD

**Issue by TheCrowned** [plausible/hosting#62]
I believe the javascript snippet we get to paste before </head> is wrong. Currently, it is this

```javascript
<script defer data-domain="localhost" src="http://localhost/js/script.js"></script>
```

but script.js does not exist at that location, since Plausible will run on port 8000 by default.

(A spinoff of https://github.com/plausible/docs/issues/331)

**Comment by ruslandoga** [comment]
@TheCrowned 👋

What do you think should be shown instead?

**Comment by ruslandoga** [comment]
The problem seems to come from `BASE_URL` being used both to configure the port to run and for URL generation in the app. We can potentially separate them into `PORT` and `HOST` while keeping `BASE_URL` for backwards compatibility with `PORT` and `HOST` taking precedence.

**Comment by satonotdead** [comment]
So we need to update our URLS (after moved to CE) to localhost, including the scripts? May I know why we can't continue using the https secured domain?

I'm with this issue from weeks/months.

**Comment by ruslandoga** [comment]
👋 @satonotdead 

As far as I remember `localhost` here was used as an example. The issue was about the port. 

You don't need to update your URLs to `localhost` when using CE.
