### ISSUE TITLE
s390x architecture

### ISSUE THREAD

**Issue by CKBTester** [plausible/hosting#81]
Is there a build method for the s390x architecture? I tried 'docker pull --platform linux/x86_64' and after downloading, the logs showed an error: "/entrypoint.sh: exec format error."

**Comment by ruslandoga** [comment]
Right now `plausible/analytics` only has `arm64` and `x86_64` builds. You can build the container images for Plausible and ClickHouse yourself, I think.

Might be relevant: https://clickhouse.com/docs/en/development/build-cross-s390x

**Comment by ruslandoga** [comment]
Ah no, `hexpm/elixir` doesn't have `s390x` builds. So you'd need to modify the Dockerfile for Plausible to use some other base image.

**Comment by ruslandoga** [comment]
Closing as only `arm64` and `x86_64` archs are currently supported.
