### ISSUE TITLE
bytemark/smtp container is outdated and abandoned

### ISSUE THREAD

**Issue by rmens** [plausible/hosting#86]
There are several problems with the `bytemark/smtp` container used for e-mail:

- It's running Debian 9 which has been deprecated in 2020
- It doesn't support ARM64
- It's maintainer, Bytemark hosting, is unresponsive and seems to have abandoned the image

May I suggest switching to another Exim relay Docker image that is well maintained like `devture/exim-relay`.

**Comment by ruslandoga** [comment]
👋 @rmens 

The next release would support direct emails (where no smart host/relay is used) and `bytemark/smtp` would not be necessary.
