### ISSUE TITLE
Request for Renaming this Repo to Plausible CE

### ISSUE THREAD

**Issue by surapuramakhil** [plausible/hosting#91]
Please do not submit issues here. Best place for self-hosting issues, questions and ideas is [the community forum here on GitHub](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

Repository name community-edition is not stand Alone. I need to perform mkdir plausible before cloning this

**Comment by ruslandoga** [comment]
@surapuramakhil 👋

> Repository name community-edition is not stand Alone.

What do you mean by this exactly?

---

Creating a directory and cloning into it is a one time operation. Is this really that bad? :)

```console
$ mkdir your-directory
$ cd your-directory
$ git clone https://github.com/plausible/community-edition .
Cloning into 'community-edition'...
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 280 (delta 106), reused 86 (delta 71), pack-reused 134
Receiving objects: 100% (280/280), 69.44 KiB | 7.71 MiB/s, done.
Resolving deltas: 100% (136/136), done.
$ ls
README.md           clickhouse/         docker-compose.yml  images/             plausible-conf.env  reverse-proxy/      upgrade/
```

**Comment by surapuramakhil** [comment]
if i clone this repository my folder name is community-edition. if i come back to this a year later - only see name community edition but id doesn't say much. I need to check folder contents to know what it is

**Comment by azasypkin** [comment]
> if i clone this repository my folder name is community-edition. if i come back to this a year later - only see name community edition but id doesn't say much. I need to check folder contents to know what it is

Just use `git clone git@github.com:plausible/community-edition.git plausible-ce`, no?

**Comment by surapuramakhil** [comment]
> @ruslandoga 
> 
> Creating a directory and cloning into it is a one time operation. Is this really that bad? :)
> 

this is my point . **if repo name is stand alone then I don't need to this**. I agree its onetime task. too small task. There are plenty of "Easy ways" to get this. 

this is just my suggestion / feedback / contribution.
