### ISSUE TITLE
Events are Not getting tracked.

### ISSUE THREAD

**Issue by surapuramakhil** [plausible/hosting#92]
Please do not submit issues here. Best place for self-hosting issues, questions and ideas is [the community forum here on GitHub](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

I am testing plausible and trying to integrate to my web App. Added tracker script. everything is running smooth on client side. There are no errors in docker logs. but No events are getting detected.

No Error on Client side from plausible
![image](https://github.com/plausible/community-edition/assets/9161543/98b34c75-4ce1-419a-abe3-6ceae14d6547)

check for existence of my tracker scripts in browser
As script https://<from my domain>/js/script.js is loaded into by browser. I can see it from browser inspect -> sources

I am testing in my local web app.

I am using UI but nothing is happening in plausible. "it says Waiting for first pageview on problempulse.store"

**Comment by ruslandoga** [comment]
👋 @surapuramakhil 

Please share your setup, configs, logs, and anything else that's relevant :)

---

<sup>P.S. questions usually go to to https://github.com/plausible/analytics/discussions/categories/self-hosted-support</sup>

**Comment by surapuramakhil** [comment]
setup is default setup. have created my own basekey as instructed in docs. connected it to my domain

**Comment by ruslandoga** [comment]
Console logs show "Ignoring event: localhost"

**Comment by surapuramakhil** [comment]
In order to test integration. I need to deploy it?

**Comment by ruslandoga** [comment]
~~I guess. It's probably a side effect of https://plausible.io/docs/excluding, I'll need to look into it to say for sure, though.~~

**Comment by aerosol** [comment]
https://plausible.io/docs/script-extensions#all-our-script-extensions
